topic:
#  name-update: ${spring.config.activate.on-profile}-user-name
  incoming:
    user:
      name-update: user-name
    chat:
      message: websocket-chat-message-streams
  outgoing:
    chat:
      save:
        message: mirror-view-save-chat
