spring:
  config:
    import: application-topic.yml
  main:
    web-application-type: reactive
  application:
    name: ${spring.config.activate.on-profile}-orchestrator
  r2dbc:
    url: r2dbc:mysql://${mysql.host}:3306/orchestrator
    username: ${RDBMS_USERNAME}
    password: ${RDBMS_PASSWORD}
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    url: jdbc:mysql://${mysql.host}:3306/orchestrator
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: ${consume.kafka.bootstrap.server}
    consumer:
      group-id: ${spring.application.name}

mysql:
  driver: jdbc:mysql://
  host: ${RDBMS_URL}
  port: 3306
  schema: orchestrator

# consume
consume:
  auth:
    database:
      host: ${AUTH_RDBMS_URL}
      user: ${AUTH_RDBMS_USER}
      password: ${AUTH_RDBMS_PASSWORD}
  kafka:
    bootstrap:
      server: ${KAFKA_HOST}