spring:
  config:
    activate:
      on-profile: local
  r2dbc:
    username: root
    password: 1234
mysql:
  host: localhost

consume:
  auth:
    database:
      host: localhost
      user: root
      password: 1234

  kafka:
    bootstrap:
      server: localhost:9092