@startuml
!define RECTANGLE class

participant "Kafka Broker" as Kafka
participant "Kafka Streams\nApp" as Streams
participant "Redis\nPub/Sub" as Redis
participant "Service A" as A
participant "Service B" as B

== 이벤트 수집 및 집계 ==
Kafka -> Streams : input topic message(serviceName, statusCode)
Streams -> Streams : aggregate per-1m window\ncalculate total, success, failure\ncompute failureRate = failure/total

== 실패율 임계치 검사 ==
alt request > minimum_request && failureRate > THRESHOLD
    Streams -> Redis : PUBLISH channel="circuit:grpc:<serviceName>"\nmessage="{"state":"open"}"
    note right of Streams: Redis Pub/Sub 로 알림 전송

    Redis -> A : SUBSCRIBE "circuit:grpc:<serviceName>"\nonMessage("open")
    A -> A : openCircuitBreaker(service)

    Redis -> B : SUBSCRIBE "circuit:grpc:<serviceName>"\nonMessage("open")
    B -> B : openCircuitBreaker(service)
else if failureRate ≤ THRESHOLD
    Streams -> Redis : PUBLISH channel="circuit:close:<serviceName>"\nmessage="{"state":"close"}"
    note right of Streams: 정상 복구 시 알림 전송
    Redis -> A : SUBSCRIBE "circuit:grpc:<serviceName>"\nonMessage("close")
        A -> A : closeCircuitBreaker(service)

        Redis -> B : SUBSCRIBE "circuit:grpc:<serviceName>"\nonMessage("close")
        B -> B : closeCircuitBreaker(service)
else

end

@enduml
